package com.internetstore.entity;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents a user's address stored in MongoDB.
 * Each user can have multiple addresses.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "addresses") // MongoDB collection name
public class Address {

    /**
     * Unique identifier for the address.
     * Automatically generated by MongoDB if not provided.
     */
    @Id
    private String id;

    /**
     * The ID of the user who owns this address.
     * Use this to query addresses for a specific user.
     */
    private String userId;

    /**
     * Street information for the address.
     * e.g., "123 Main St, Apt 4B"
     */
    private String street;

    /**
     * City name
     */
    private String city;

    /**
     * State or province
     */
    private String state;

    /**
     * ZIP or postal code
     */
    private String zipCode;

    /**
     * Country name
     */
    private String country;
    /**
     * Indicates if this address is the default for the user.
     * Each user should have at most one default address.
     */
    private boolean isDefault;

    // Optional Improvement: You could add timestamps for auditing
    // @CreatedDate
    // private Instant createdAt;
    //
    // @LastModifiedDate
    // private Instant updatedAt;
}
