package com.internetstore.entity;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a shopping cart for a specific user.
 * Stores a list of CartItem objects and calculates total price.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "carts")
public class Cart {

    /**
     * Unique identifier for the cart.
     * Automatically generated by MongoDB if not provided.
     */
    @Id
    private String id;

    /**
     * ID of the user who owns this cart.
     */
    private String userId;

    /**
     * List of items in the cart.
     * Initialized to an empty list by default to avoid NullPointerExceptions.
     */
    @Builder.Default
    private List<CartItem> items = new ArrayList<>();

    /**
     * Total price of all items in the cart.
     * Should be updated whenever items are added/removed/updated.
     */
    private BigDecimal totalPrice;

    /**
     * Timestamp of the last update to the cart.
     * Useful for cache expiration, auditing, or showing "last updated" in UI.
     */
    private LocalDateTime updatedAt;

    // Optional improvements:

    // 1. Automatically set `updatedAt` on modification
    // @PrePersist / @PreUpdate can be used if using JPA,
    // or update manually in service layer for MongoDB.

    // 2. Ensure totalPrice is never null
    // Can initialize in builder or constructor: totalPrice = BigDecimal.ZERO;

    // 3. Consider using BigDecimal.ZERO instead of null by default
    @Builder.Default
    private BigDecimal totalPriceSafe = BigDecimal.ZERO;
}
